version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"  # Changez 3000 en 3001 ici
    env_file:
      - .env
    environment:
      - NODE_ENV=production

volumes:
  mysql_data: